const classAnswers = [
  {
    month: "APRIL",
    items: [
      { date: "4/8", question: "What phrase symbolizes summer!?", answer: "Vivid carp streamers." },
      { date: "4/18", question: "The places where people dumped their waste in the Jomon period — what are they called nowadays?", answer: "Middens." },
      { date: "4/27", question: "Protagonist, do you know which one's not an algebraic spiral or whatever?", answer: "A." }
    ]
  },
  {
    month: "MAY",
    items: [
      { date: "5/6", question: "What do you call the device that helps generate electric power for trains?", answer: "A pantograph." },
      { date: "5/13", question: "Which tool did he use in his experiments?", answer: "The pendulum." },
      { date: "5/15", question: "What's the other name for \"May sickness\" — the more casual one?", answer: "May Blues." },
      { date: "5/19 (Exam)", question: "What is the other common expression used to describe \"May sickness\"?", answer: "May Blues" },
      { date: "5/20 (Exam)", question: "Which of the following did Léon Foucault use in his experiment on the rotation of the Earth?", answer: "A pendulum" },
      { date: "5/21 (Exam)", question: "Which of the following is generated by a pantograph?", answer: "Electricity" },
      { date: "5/22 (Exam)", question: "During which historical period were middens most commonly used?", answer: "Jomon" }
    ]
  },
  {
    month: "JUNE",
    items: [
      { date: "6/15", question: "Which phrase means, \"able to see things for what they really are\"?", answer: "Keen eye." },
      { date: "6/17", question: "What early religious practice was the origin of magic?", answer: "Shamanism." },
      { date: "6/22", question: "What else do people call this curve?", answer: "Witch of Agnesi." },
      { date: "6/25", question: "What's it called when the air bubbles in a whirlpool bath hit you and make your body vibrate?", answer: "The flutter effect." },
      { date: "6/29", question: "What form of natural magic is used to find water sources?", answer: "Dowsing." }
    ]
  },
  {
    month: "JULY",
    items: [
      { date: "7/3", question: "H-Hey, lend me a hand here, Protagonist. What kinda tale is he talkin' about?", answer: "About romance." },
      { date: "7/8", question: "\"Because it is 10:30 right now, we will not reach the theater in time, it's already started, to my dismay.\"", answer: "Between \"time\" and \"it's.\"" },
      { date: "7/9", question: "At the same time, a serious problem arose for the farmers. Do you remember what that was?", answer: "Social disparity." },
      { date: "7/10", question: "What is the esoteric study of Jewish texts called?", answer: "Kabbalah." },
      { date: "7/11", question: "Now, what do you think that item was? It's something every samurai needs!", answer: "The katana." },
      { date: "7/14 (Exam)", question: "Which form of magic is used to find water sources?", answer: "Dowsing" },
      { date: "7/15 (Exam)", question: "How did the Witch of Agnesi gain the first half of its name?", answer: "An error in translation" },
      { date: "7/16 (Exam)", question: "Who designed the prototype for the katana?", answer: "Taira No Masakado" },
      { date: "7/17 (Exam)", question: "There is an error in this sentence, what kind is it?", answer: "Comma splice" }
    ]
  },
  {
    month: "SEPTEMBER",
    items: [
      { date: "9/1", question: "Which property of electricity is relevant to superconductivity?", answer: "Resistance." },
      { date: "9/10", question: "H-Hey, Protagonist, do you know what it means to \"spill the beans\"?", answer: "To reveal a secret." },
      { date: "9/11", question: "Which book helped further the art of magic during the Renaissance?", answer: "The Hermetica." },
      { date: "9/14", question: "Who is one referring to when speaking of their \"better half\"?", answer: "Their soulmate." },
      { date: "9/26", question: "What is the collective naming for the four holy numbers in numerology?", answer: "Tetractys." }
    ]
  },
  {
    month: "OCTOBER",
    items: [
      { date: "10/7", question: "Which hormone is the one in your brain that provides a sense of achievement?", answer: "Dopamine." },
      { date: "10/10", question: "Who was the founder of Theosophy, a group that gave rise to many other magical societies?", answer: "Helena Blavatsky." },
      { date: "10/13 (Exam)", question: "The hormone dopamine is related to our sense of accomplishment. Name a symptom of its over-production.", answer: "Addiction." },
      { date: "10/14 (Exam)", question: "Who is considered by many to be the first numerologist, whose name lives on today in a mathematical theorem?", answer: "Pythagoras." },
      { date: "10/15 (Exam)", question: "What happens when electrical resistance reaches zero? Hint: It was the word I used to confess my love to someone...", answer: "Superconductivity." },
      { date: "10/16 (Exam)", question: "What is the meaning of the phrase \"to spill the beans\"?", answer: "To reveal a secret." },
      { date: "10/19", question: "We use the number \"zero\" a lot. Do you know where it originally came from, though?", answer: "India." },
      { date: "10/22", question: "Which Roman goddess has been theorized as the namesake for the month of April?", answer: "Venus." },
      { date: "10/26", question: "But there's one region that instead calls it \"the month with gods,\" because that's where they all go! Do you know which one it is?", answer: "Izumo." },
      { date: "10/30", question: "A certain enzyme brings out the sweetness in them when they're baked. Do you happen to know what it is?", answer: "Beta-amylase." }
    ]
  },
  {
    month: "NOVEMBER",
    items: [
      { date: "11/7", question: "What is the ancient Indian magical text I mentioned today?", answer: "The Upanishads." },
      { date: "11/12", question: "What was she describing with such a sparse line?", answer: "Her favorite time in winter." },
      { date: "11/30", question: "In the poem that Genji, the protagonist, sends to her, what did he compare her to?", answer: "The cherry blossom." }
    ]
  },
  {
    month: "DECEMBER",
    items: [
      { date: "12/7", question: "What's the name of the stratospheric layer of molecules comprised of three oxygen atoms?", answer: "The ozone layer." },
      { date: "12/9", question: "What sorcery was Himiko said to have used?", answer: "Kido." },
      { date: "12/11", question: "Do you know which of the following is an irregular plural noun?", answer: "Lives." },
      { date: "12/14 (Exam)", question: "Which of the following originated in India?", answer: "The number zero." },
      { date: "12/15 (Exam)", question: "When heated, the beta-amylase enzymes in sweet potatoes react with the starch present to produce which disaccharide?", answer: "Maltose." },
      { date: "12/16 (Exam)", question: "Which roman goddess has been theorized as the namesake for the month of April?", answer: "Venus." },
      { date: "12/17 (Exam)", question: "In The Tale of Genji, who does Hikaru Genji compare to cherry blossoms?", answer: "Murasaki-no-Ue." },
      { date: "12/18 (Exam)", question: "Which of the following words is not in the correct plural form?", answer: "Geeses." },
      { date: "12/22", question: "What do we call the feeling of joy that comes from a near-death experience?", answer: "Euphoria." }
    ]
  },
  {
    month: "JANUARY",
    items: [
      { date: "1/8", question: "\"The new year is the index of a journey to a certain place.\" Where is this \"certain place\" he's referring to?", answer: "The underworld." },
      { date: "1/18", question: "I've mentioned two Greek sorceresses. One was Medea. Who was the other?", answer: "Circe." }
    ]
  }
];
